### ISSUE TITLE
Importing local Images return string instead of the nextJs image obj

### ISSUE THREAD

**Issue by Hyra10** [payloadcms/next-payload#1]
I was trying this plugin out, I know it is not production ready, but I noticed that if you import an image hosted locally

the normal 
`import RandomName from 'path/to/Image.png'`

 it will return a string instead of the normal NextJs image obj
example of what it should return:

```
{
  src: '/_next/static/media/image.png',
  height: 1057,
  width: 2061,
  blurDataURL: '/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fimage1.0f59ede4.png&w=8&q=70',
  blurWidth: 8,
  blurHeight: 4
}
```

what it returns 

`'/_next/static/media/image.png',`

**Comment by jmikrut** [comment]
Hey @Hyra10 — good catch! This is fixed now. 👍
