### ISSUE TITLE
Content in Globals disappearing after save

### ISSUE THREAD

**Issue by arieltonglet** [payloadcms/next-payload#14]
## Describe the bug
After hitting "Save" button, Content is saved but disappears from browser. Refreshing the page loads the updated content.

## To Reproduce
- Cloned `next-payload-demo`
- Changed .env leaving only `S3` blank:
```
MONGODB_URI=mongodb://localhost/payload-vercel-functions
PAYLOAD_SECRET=YOUR_SECRET_HERE
PAYLOAD_CONFIG_PATH=dist/payload.config.js
NEXT_PUBLIC_APP_URL=http://localhost:3000
PAYLOAD_PUBLIC_CMS_URL=http://localhost:3000
S3_ACCESS_KEY_ID=
S3_SECRET_ACCESS_KEY=
S3_REGION=
NEXT_PUBLIC_S3_ENDPOINT=
NEXT_PUBLIC_S3_BUCKET=
PAYLOAD_PRIVATE_REGENERATION_SECRET=123123
NEXT_PRIVATE_REGENERATION_SECRET=123123
```

- Run `yarn dev`
- Make a change in Main Menu -> Nav Items

## Expected behavior
Updated content should be still visible after save.

## Screenshots/Video
https://user-images.githubusercontent.com/13951624/232585056-2674a630-e8e7-43dc-9b9e-ebb7a1a35b1b.mp4

## Additional context
Thread in community-help: https://discord.com/channels/967097582721572934/1096539580687200347

**Comment by JarrodMFlesch** [comment]
This has been fixed and will be in the next release. Thanks for reporting!
