### ISSUE TITLE
TypeError: tag[primaryAttributeKey].toLowerCase is not a function

### ISSUE THREAD

**Issue by frrrt** [payloadcms/next-payload#16]
The error occurs with the standard setup of nextjs and next-payload. 

This is what I have done:
1. yarn create next-app (yes to everything but tailwind)
2. follow this guide steps 1-3 (step 4 looks off in the guide but correct in code): https://github.com/payloadcms/next-payload 
3. Opening http://localhost:3000/admin/login

I get this error:
```
Unhandled Runtime Error
TypeError: tag[primaryAttributeKey].toLowerCase is not a function

Call Stack
eval
node_modules\react-helmet\es\Helmet.js (253:0)
Array.filter
<anonymous>
eval
node_modules\react-helmet\es\Helmet.js (232:0)
Array.reduce
<anonymous>
getTagsFromPropsList
node_modules\react-helmet\es\Helmet.js (229:5)
reducePropsToState
node_modules\react-helmet\es\Helmet.js (305:0)
emitChange
node_modules\react-side-effect\lib\index.js (56:0)
SideEffect.UNSAFE_componentWillMount
node_modules\react-side-effect\lib\index.js (97:0)
```

What am I doing wrong here? 😄 

I think also kind of missing is setting up the `/css/my-custom-payload-styles.css` either from the install script or mentioning that in the guide.

Btw. if this works, it is literally a dream come true for me, keep up the great work! 👍

**Comment by JarrodMFlesch** [comment]
@frrrt I spent a bit of time in here yesterday and was unable to replicate. I will give it a go from scratch right now 👍

**Comment by frrrt** [comment]
Hi @JarrodMFlesch ! Thanks for looking into it!

I tried some different things to get around the problem:
- updated all packages
- used the docker compose setup (with a clean DB) from here https://payloadcms.com/docs/production/deployment#docker

But still the same result unfortunately.

**Comment by frrrt** [comment]
Interesting! If I dont just run `docker compose up -d mongo` but `docker compose` it works :)

**Comment by dawnchan030920** [comment]
I'm confronted with this problem too. Is there any solution to it other than using Docker?

**Comment by johannesschaffer** [comment]
+1 Same problem here. Not using docker btw, but a hosted version (Atlas)

**Comment by johannesschaffer** [comment]
@JarrodMFlesch Would a reproduction help, or could you reproduce it by now? 
I don't currently have one at hand, but I'm pretty sure the same thing occurred in the next-payload-demo repo, so I probably could make some ready.

**Comment by JarrodMFlesch** [comment]
@johannesschaffer A reproduction would be amazing. I have tried to reproduce but have been unable to, even following the steps listed above from @frrrt 😕

**Comment by johannesschaffer** [comment]
@JarrodMFlesch I could reproduce it with a fresh fork of the next-payload-demo repo. I just go to /admin. For a while the loading spinner shows, then I get the error.
Repo: https://github.com/johannesschaffer/next-payload-demo
- I tried it with both yarn & npm. Same error.
- For my repro to work tou only need to have a local MongoDB instance, no S3 required - Doesn't even get to that step - I didn't modify .env at all.
- My environment: 
  - OS: Windows 11
  - node: 18.12.1
  - yarn: 3.4.1
  - npm: 9.6.2

**Comment by JarrodMFlesch** [comment]
Thanks @johannesschaffer!

Curious @frrrt what does your environment look like?

**Comment by CypressJack** [comment]
@JarrodMFlesch @johannesschaffer 

A workaround for this issue is to add `public/favicon.ico` file and define it in your payload config object.

```javascript
export default buildConfig({
  admin: {
    meta: {
      favicon: '/favicon.ico'
    }
  }
  // other config options
});
```

The error is being triggered in payload's admin/components/Meta component [Meta.tsx](https://github.com/payloadcms/payload/blob/master/src/admin/components/utilities/Meta/index.tsx)

The `favicon` variable is being passed to `href` as an object, getting past react-helmet's `null` check, but throwing the error when the string method `.toLowerCase()` is being called on it. Overriding the `favicon` variable with a string in payload.config.ts just guarantee's the `.toLowerCase()` method exists when react-helmet calls it.

I can confirm I don't get this error on Linux Mint, but a colleague was facing it on Windows 10 when we found this workaround. Maybe has to do with how file-paths are resolved and returned in import statements on Windows vs Linux? Not too sure yet.

```javascript
import React from 'react';
import Helmet from 'react-helmet';
import { useConfig } from '../Config';
import { Props } from './types';
import payloadFavicon from '../../../assets/images/favicon.svg';
import payloadOgImage from '../../../assets/images/og-image.png';
import useMountEffect from '../../../hooks/useMountEffect';

const Meta: React.FC<Props> = ({
  description,
  lang = 'en',
  meta = [],
  title,
  keywords = 'CMS, Admin, Dashboard',
}) => {
  const config = useConfig();
  const titleSuffix = config.admin.meta?.titleSuffix ?? '- Payload';
  // We can see here why overriding the favicon as a string path in payload.config.ts removes the .toLowerCase() react-helmet error
  const favicon = config.admin.meta.favicon ?? payloadFavicon; 
  const ogImage = config.admin.meta.ogImage ?? payloadOgImage;

  useMountEffect(() => {
    const faviconElement = document.querySelector<HTMLLinkElement>('link[data-placeholder-favicon]');
    if (faviconElement) {
      faviconElement.remove();
    }
  });

  return (
    <Helmet
      htmlAttributes={{
        lang,
      }}
      title={`${title} ${titleSuffix}`}
      meta={[
        {
          name: 'description',
          content: description,
        },
        {
          name: 'keywords',
          content: keywords,
        },
        {
          property: 'og:title',
          content: `${title} ${titleSuffix}`,
        },
        {
          property: 'og:image',
          content: ogImage,
        },
        {
          property: 'og:description',
          content: description,
        },
        {
          property: 'og:type',
          content: 'website',
        },
        {
          name: 'twitter:card',
          content: 'summary',
        },
        {
          name: 'twitter:title',
          content: title,
        },
        {
          name: 'twitter:description',
          content: description,
        },
      ].concat(meta)}
      link={[
        {
          rel: 'icon',
          type: 'image/svg+xml',
          // Here is where the error is triggered by passing an object to href
          href: favicon, 
        },
      ]}
    />
  );
};

export default Meta;
```

**Comment by johannesschaffer** [comment]
Can confirm @CypressJack workaround works for me 👍

**Comment by jmikrut** [comment]
Hey all, this is now fixed and released! Thank you everyone for your feedback. It was an issue with our Webpack config and how it used a regex pattern to handle files. We've improved a regex pattern which now handles files accordingly for both Windows and Unix-like paths.

**Comment by johannesschaffer** [comment]
@jmikrut Since the fix involces a regex starting with /node_modules/... - Would this work in monorepos with npm (the path to node_modules would be ../../node_modules)?
