### ISSUE TITLE
useAPIKey doesn't work

### ISSUE THREAD

**Issue by johannesschaffer** [payloadcms/next-payload#25]
When using `auth: {useAPIKey}` in the `Users` collecition, I can't log in. Payload says I don't have authorization.

**Comment by jmikrut** [comment]
Hey @johannesschaffer — this is now fixed and will be released shortly. Thank you for your patience and for reporting the issue!

**Comment by johannesschaffer** [comment]
Great! Would have been nice though, to get some updates or time frame. Just a tip for the future 😉

**Comment by jmikrut** [comment]
Absolutely. This one was open for too long and generally we will try to be much faster at fixes. At the very least will communicate plans more clearly. Thanks again for hanging in there
