### ISSUE TITLE
No Email integration

### ISSUE THREAD

**Issue by NardiniA** [payloadcms/next-payload#28]
Unlike the server version, the serverless Payload CMS does not allow for email integration through the Next JS API. This means no password recovery and unable to effectively use the FormBuilder plugin to handle forms.

**Comment by JessChowdhury** [comment]
Hi @NardiniA, next-payload does support email integration - are you having a specific problem setting up your email?

Instead of passing your email options to `payload.init()` you will pass it to `getPayload({})` in the `payloadClient.ts` like this:

```ts
  if (!cached.promise) {
    cached.promise = await getPayload({
      // Make sure that your environment variables are filled out accordingly
      mongoURL: process.env.MONGODB_URI as string,
      secret: process.env.PAYLOAD_SECRET as string,
      config: config,
      email: {
        fromAddress: 'admin@test.com',
        fromName: 'Admin',
        logMockCredentials: true,
      }
    })
  }
```

**Comment by NardiniA** [comment]
I've got that however, whenever you try to send an email using the forgot password feature you receive this error:

```
ERROR (payload): TypeError: t is not a function
    at forgotPassword (webpack-internal:///(api)/./node_modules/payload/dist/auth/operations/forgotPassword.js:44:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async handler (webpack-internal:///(api)/./node_modules/@payloadcms/next-payload/dist/handlers/[collection]/forgot-password.js:30:9)
```

This happens with `logMockCredentials' and also when you set transport options set using smtp.

**Comment by JessChowdhury** [comment]
Thanks for sending the error message, that gives us a lot more to go on!

This issue is specific to our forgot password function, we look into this right away - this should not affect other email functionality.

**Comment by JarrodMFlesch** [comment]
Hey @NardiniA this has been fixed as of `v1.0.15` if you want to give that a shot 👍

**Comment by JarrodMFlesch** [comment]
Fixed in latest

**Comment by ficeco** [comment]
> Hi @NardiniA, next-payload does support email integration - are you having a specific problem setting up your email?
> 
> Instead of passing your email options to `payload.init()` you will pass it to `getPayload({})` in the `payloadClient.ts` like this:
> 
> ```ts
>   if (!cached.promise) {
>     cached.promise = await getPayload({
>       // Make sure that your environment variables are filled out accordingly
>       mongoURL: process.env.MONGODB_URI as string,
>       secret: process.env.PAYLOAD_SECRET as string,
>       config: config,
>       email: {
>         fromAddress: 'admin@test.com',
>         fromName: 'Admin',
>         logMockCredentials: true,
>       }
>     })
>   }
> ```

Would this work for a postgres database? Also when inserting the solution as is, I get an error saying "'mongoURL' does not exist in type 'InitOptions'"
