### ISSUE TITLE
No Typescrip types in the middleware folder

### ISSUE THREAD

**Issue by johannesschaffer** [payloadcms/next-payload#3]
No types in @payloadcms/next-payload/middleware. This causes a problem with typescript when importing them.

**Comment by ameesme** [comment]
While this is unfortunate, it can temporarily be circumvented by setting `"strict": false` in your `tsconfig.json`.

**Comment by jmikrut** [comment]
We have a fix for this one coming probably tomorrow or Wednesday! Just a quick update.

**Comment by ameesme** [comment]
Sweet! Looking forward to it.

**Comment by johannesschaffer** [comment]
Great. Setting strict to false however, doesn't always work, since it reduces it's type inference capabilities and is required by some libraries (e.g. Zod).

**Comment by JarrodMFlesch** [comment]
We adjusted how the code is handled. Now it is imported from the package, this way code changes can happen inside those handlers when the plugin is updated which is nice.

You will need to run `yarn next-payload install` and read through the updated readme!

**Comment by ameesme** [comment]
Thanks for the update and fix!
