### ISSUE TITLE
Relationships and Uploads disappearing in Globals after save

### ISSUE THREAD

**Issue by arieltonglet** [payloadcms/next-payload#30]
## Describe the bug
I guess this is related to issue #14 

After hitting "Save" button, text content is saved but relationships and upload disappears from browser. 
Refreshing the page loads up the previously saved content.

## To Reproduce
- Cloned `next-payload-demo`
- Changed .env and configured GCS for media
- Added relationship and upload fields
- Run `yarn dev`
- Make a change in fields and save

## Expected behavior
Updated content should be still visible after save.

## Screenshots/Video
https://github.com/payloadcms/next-payload/assets/13951624/aad6a805-6d89-44ce-8dd6-196c79484158

**Comment by arieltonglet** [comment]
Hey guys, could you reproduce this? I ended up having to add a custom save button that reloads the page after save (_kind of_ sidestepping the problem, but not pretty at all)

This could look like a minor bug, but: if the field in question is not required and the user is not paying attention to it, saving the global a second time will erase all data from these fields. 

It was frustrating to find out what was happening, because some data was being (seemingly randomly) erased. At first I even thought it was a DB error :/

If the field is required, the user will get a lot of errors when trying to save it again.

Anyway, just wanted to check on this :)

**Comment by jmikrut** [comment]
Hey @arieltonglet — sorry for the delay in response here! This is now fixed and released. Just update and you should be good to go.

Also, we plan to put more time and energy into this repo, so you should see future fixes coming in at a more consistent rate. Thanks again for hanging in here.

**Comment by arieltonglet** [comment]
Hi @jmikrut tanks a lot for the fix! So glad to hear that next-payload will be getting more attention :)
