### ISSUE TITLE
API Reset Password Got Type Error

### ISSUE THREAD

**Issue by WilsonLe** [payloadcms/next-payload#37]
Following the standard setup procedure and using the RestAPI documentation (https://payloadcms.com/docs/rest-api/overview#auth-operations) on reset user password after receiving a reset token yields the following error:

The request:

![Screenshot 2023-06-14 at 11 57 22 PM](https://github.com/payloadcms/next-payload/assets/43991506/c6c407aa-135c-433a-9ab7-645ae82a76a2)

```
[16:50:41] ERROR (payload): TypeError: args.res.cookie is not a function
    at resetPassword (webpack-internal:///(api)/./node_modules/payload/dist/auth/operations/resetPassword.js:81:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async handler (webpack-internal:///(api)/./node_modules/@payloadcms/next-payload/dist/handlers/[collection]/reset-password.js:26:24)
```

The specific line that cause this error:

```
// node_modules/payload/dist/auth/operations/resetPassword.js

if (args.res) {
    const cookieOptions = {
        path: '/',
        httpOnly: true,
        expires: (0, getCookieExpiration_1.default)(collectionConfig.auth.tokenExpiration),
        secure: collectionConfig.auth.cookies.secure,
        sameSite: collectionConfig.auth.cookies.sameSite,
        domain: undefined,
    };
    if (collectionConfig.auth.cookies.domain)
        cookieOptions.domain = collectionConfig.auth.cookies.domain;
    args.res.cookie(`${config.cookiePrefix}-token`, token, cookieOptions); // <----- error here
}
```

Since this error occur after payload updates user with new password, the intended functinality is achieved. The only problem is that now the API request will return status 500, which is not ideal.

**Comment by jmikrut** [comment]
Hey @WilsonLe — thank you for the report! Easy fix. A new version will be coming out shortly. 👍
