### ISSUE TITLE
Can the local API use the user token for access control?

### ISSUE THREAD

**Issue by ahaasler** [payloadcms/next-payload#39]
Hi,

is there a way of using the local API with `overrideAccess: false,` and setup the user via the `payload-token`?

I don't seem to find on the docs the proper way of requesting content only the user can see via the local API.

I'm looking for something like this:

```typescript
import {notFound} from "next/navigation";
import {getPayloadClient} from "@/content/payloadClient";
import {Post} from "@/content/types";
import RichText from "@/components/RichText";
import { cookies } from 'next/headers'

interface PostPageProps {
	params: {
		slug: string
	}
}

export default async function PostPage({params}: PostPageProps) {
	const post = await getPostBySlug(params.slug)
	if (!post) return notFound();
	return <div>
		<h1>{post.title}</h1>
		<RichText content={post.content}/>
	</div>
};

async function getPostBySlug(slug: string): Promise<Post> {
	const payload = await getPayloadClient();
	const cookieStore = cookies()
	const posts = await payload.find({
		collection: "posts",
		overrideAccess: false,
		user: {
			token: cookieStore.get("payload-token").value
		},
		where: {
			slug: {
				equals: slug,
			},
		},
	});
	return posts.docs[0];
}
```

I've successfully used `payload.login` to get a user document that can be used for this kind of user control, but this is not something I can do because this is the server-generated page and the cookie token of an already logged-in user should be used to set up access control in the local API.

Is that possible?

**Comment by jmikrut** [comment]
Hey @ahaasler — yes, this is totally possible. But, our local API does not accept `token` as an argument. Instead, it accepts a full `user`. 

We would certainly accept a PR that exposes a new property to our local API called `userToken` or similar, that will accept a string JWT and attempt to verify / decode it for use as a user, but right now, we only accept a user.

To decode the token and pass it as a `user` to the `payload.find` local API method, you would do something like this: 

```js
import jwt from 'jsonwebtoken';
import { notFound } from "next/navigation";
import { getPayloadClient } from "@/content/payloadClient";
import { Post } from "@/content/types";
import RichText from "@/components/RichText";
import { cookies } from 'next/headers'


async function getPostBySlug(slug: string): Promise<Post> {
  const payload = await getPayloadClient();
  const cookieStore = cookies()
  // new line to verify JWT using cookie value and payload secret
  const user = jwt.verify(cookieStore.get('payload-token').value, payload.secret)

  const posts = await payload.find({
    collection: "posts",
    overrideAccess: false,
    // just pass the user
    user,
    where: {
      slug: {
        equals: slug,
      },
    },
  });
  return posts.docs[0];
}
```

I haven't tested the above, but this should work just fine!

Give it a shot?

**Comment by ahaasler** [comment]
Hi @jmikrut, thanks for your help. It almost works out of the box.

When using roles, the user document in the token does not work for access control without including said roles.

If the role can be inferred from the email the solution is pretty easy:
```typescript
if (user?.email === "admin@test.com") {
	user.roles = ["admin"]
}
```

If that is not possible, a user search solves it:
```typescript
const userWithRoles = await payload.findByID({
	collection: "users",
	id: user?.id
})
```

But the best solution is to modify the user collection so that the roles are stored on the token with `saveToJWT: true,`:
```typescript
import type { CollectionConfig } from 'payload/types'

export const Users: CollectionConfig = {
	slug: 'users',
	auth: true,
	admin: {
		...
	},
	access: {
		...
	},
	fields: [
		...
		{
			name: 'roles',
			type: 'select',
			hasMany: true,
			saveToJWT: true,
			defaultValue: ['public'],
			required: true,
			access: {
				...
			},
			options: ['admin', 'public'],
		},
	],
}
```
