### ISSUE TITLE
Fully type "hander()" in the api routes

### ISSUE THREAD

**Issue by johannesschaffer** [payloadcms/next-payload#4]
The parameters (req & res) of the api routes in the "pages" dir (which are autogenerated by next-payload) don't have types. This makes it hard to use with Typescript strict mode (which Next.js comes with by default).

**Comment by JarrodMFlesch** [comment]
The code is now imported from the package, this way code changes can happen inside those handlers when the plugin is updated which is nice.

You will need to run `yarn next-payload install` and read through the updated readme!
