### ISSUE TITLE
@import '~payload-user-css'; fail

### ISSUE THREAD

**Issue by joelcorey** [payloadcms/next-payload#43]
`./node_modules/payload/dist/admin/scss/app.scss.webpack[javascript/auto]!=!./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[4].oneOf[13].use[2]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[4].oneOf[13].use[3]!./node_modules/next/dist/build/webpack/loaders/resolve-url-loader/index.js??ruleSet[1].rules[4].oneOf[13].use[4]!./node_modules/next/dist/compiled/sass-loader/cjs.js??ruleSet[1].rules[4].oneOf[13].use[5]!./node_modules/payload/dist/admin/scss/app.scss
SassError: Can't find stylesheet to import.
    ╷
180 │ @import '~payload-user-css';
    │         ^^^^^^^^^^^^^^^^^^^
    ╵
  node_modules/payload/dist/admin/scss/app.scss 180:9  root stylesheet`

I get this error on install. Deleting line 180 fixes it.

**Comment by okeken** [comment]
What I endup doing is creating a simple script to automatically remove this line after every installs,

`removeSassError.js`
```
const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'node_modules', 'payload', 'dist', 'admin', 'scss', 'app.scss');

fs.readFile(filePath, 'utf8', (err, data) => {
  if (err) {
    console.error('Error reading the file:', err);
    return;
  }

  const lines = data.trim().split('\n');

  if (lines[lines.length - 1].includes('@import \'~payload-user-css\';')) {
    // Remove the last line
    lines.pop();

    const modifiedContent = lines.join('\n');

    fs.writeFile(filePath, modifiedContent, 'utf8', (err) => {
      if (err) {
        console.error('Error writing to the file:', err);
        return;
      }
      console.log('Last line removed successfully!');
    });
  } else {
    console.log('Last line does not contain the import, no action needed.');
  }
});


```

inside my `package.json`

```
 "scripts": {
    "postinstall": "yarn removeError",
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "removeError": "node removeSassError.js"
  },
```

**Comment by JarrodMFlesch** [comment]
@joelcorey are you getting this on the latest version? I am unable to reproduce, but would love to help if you can provide a bit more info!

**Comment by lufehr** [comment]
@joelcorey @KobeIndemans  have you tried to remove the following line from `next.config.js` if you haven't a custom css file present?

```javascript
    // Point to custom Payload CSS (optional)
    cssPath: path.resolve(__dirname, "./css/my-custom-payload-styles.css"),
```

**Comment by JarrodMFlesch** [comment]
> @joelcorey @KobeIndemans have you tried to remove the following line from `next.config.js` if you haven't a custom css file present?
> 
> ```js
>     // Point to custom Payload CSS (optional)
>     cssPath: path.resolve(__dirname, "./css/my-custom-payload-styles.css"),
> ```

Yes this is the issue, you need to remove this line. The next release will log a warning and prevent the app from breaking, though.
