### ISSUE TITLE
NextJS App Stuck on "Loading" overlay during first register.

### ISSUE THREAD

**Issue by IAmNatch** [payloadcms/next-payload#46]
I've created a new NextJS project, using the NextJS App Dir and Next-Payload. 

When I navigate to `/admin` for the first time, the page renders, but then a loading overlay appears and never resolves. I see the following error in my browser console:
`Uncaught (in promise) SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON`

I've attached a reproducible example 
here: [repro.zip](https://github.com/payloadcms/next-payload/files/12091102/repro.zip)

**Comment by imCorfitz** [comment]
@IAmNatch Your reproducible example does not include any payload related matters. It seems like a pure Next.js installation.

**Comment by IAmNatch** [comment]
@imCorfitz My apologies for wasting your time there, I appear to have zipped the wrong folder. Here is the reproduction:

[french-gossip.zip](https://github.com/payloadcms/next-payload/files/12097534/french-gossip.zip)

**Comment by IAmNatch** [comment]
Removing that resolved my issue, thanks so much!
