### ISSUE TITLE
`yarn next-payload install` doesn't check for `src` folder correctly

### ISSUE THREAD

**Issue by imCorfitz** [payloadcms/next-payload#52]
Following a recent update, `src` directory support was added, but it seems to enforce it.

https://github.com/payloadcms/next-payload/assets/52371939/b9d112c2-0551-473b-abc2-c5038be56fa7

**Comment by dawnchan030920** [comment]
Same for npm.

**Comment by JarrodMFlesch** [comment]
This has been fixed in `0.0.34` 🥳
