### ISSUE TITLE
Error: failed to handle: base_dir() must be absolute. Please ensure that `jsc.baseUrl` is specified correctly.

### ISSUE THREAD

**Issue by chrisblakely01** [payloadcms/next-payload#54]
Getting the following issue when I follow the README steps. Cloned https://github.com/payloadcms/next-payload-demo and ran as is and seeing the same. Any ideas?

```
thread '<unnamed>' panicked at 'base_dir() must be absolute. Please ensure that `jsc.baseUrl` is specified correctly.', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\swc_ecma_transforms_module-0.173.28\src\path.rs:104:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
C:\Users\Chris\code-coyotes\node_modules\@swc\core\index.js:241
            return bindings.transformSync(isModule ? JSON.stringify(src) : src, isModule, toBuffer(newOptions));
                            ^

Error: failed to handle: base_dir() must be absolute. Please ensure that `jsc.baseUrl` is specified correctly.
    at Compiler.transformSync (C:\Users\Chris\code-coyotes\node_modules\@swc\core\index.js:241:29)
    at Object.transformSync (C:\Users\Chris\code-coyotes\node_modules\@swc\core\index.js:348:21)
    at compile (C:\Users\Chris\code-coyotes\node_modules\@swc\register\lib\node.js:76:22)
    at compileHook (C:\Users\Chris\code-coyotes\node_modules\@swc\register\lib\node.js:91:16)
    at Module._compile (C:\Users\Chris\code-coyotes\node_modules\pirates\lib\index.js:113:29)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Object.newLoader [as .ts] (C:\Users\Chris\code-coyotes\node_modules\pirates\lib\index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Module.require (node:internal/modules/cjs/loader:1012:19) {
  code: 'GenericFailure'
}

Node.js v18.4.0
```

**Comment by dawnchan030920** [comment]
Confronted with the same issue

**Comment by walid-mos** [comment]
Same here, is it a bug in payload end ? Steps on this repo are pretty clear and straightforward ...

**Comment by walid-mos** [comment]
So,
I did a pull request with a hotfix for this matter : 
https://github.com/payloadcms/next-payload/pull/56

It's only a temporary fix, until payload team works on this issue, but it works for now.

**Comment by dawnchan030920** [comment]
Would you @walid-mos mind leaving some comment in Discord? This might help with solving the issue.

**Comment by revnelson** [comment]
Thanks @walid-mos this works like a charm. For anyone else it may help, I had to do the same fix to `node_modules/payload/dist/bin/index.js` line 35 from:

`swcOptions.jsc.baseUrl = tsConfig.config.compilerOptions.baseUrl;`

to:

```
swcOptions.jsc.baseUrl = path.resolve(
  tsConfig?.config?.compilerOptions?.baseUrl
);
```

**Comment by MarvinVrdoljak** [comment]
Same issue here.

**Comment by Banankiem** [comment]
Same issue here. 👀

**Comment by chrisblakely01** [comment]
> So, I did a pull request with a hotfix for this matter : #56
> 
> It's only a temporary fix, until payload team works on this issue, but it works for now.

Thanks @walid-mos much appreciated!

**Comment by JarrodMFlesch** [comment]
@walid-mos I reviewed your PR. A couple tweaks and we can merge it in.

Thanks for digging into it!

**Comment by thgh** [comment]
For those who want a solution right now, pinning swc core to this version works:

```json
 "@swc/core": "1.3.66",
```

**Comment by JarrodMFlesch** [comment]
@thgh are you on 0.0.35? The issue should be resolved in the latest verison!

**Comment by JarrodMFlesch** [comment]
@thgh gotcha! I believe the version that broke this is `1.3.76` so pinning to `1.3.75` should work, just fyi 😄

**Comment by MarvinVrdoljak** [comment]
`@swc/core` just updated to Version `1.3.77`. That one just fix the issue: https://github.com/swc-project/swc/issues/7800

**Comment by JarrodMFlesch** [comment]
@MarvinVrdoljak Thank you for the heads up!
