### ISSUE TITLE
Payload package included in main client bundle when using local api

### ISSUE THREAD

**Issue by adampilks** [payloadcms/next-payload#55]
When doing a production build of a site that uses nextjs app router and payload side by side, I have found that the full Payload package is added to the main shared client js bundle.

The only time payload is referenced in the app components is when using the local api to fetch data in server components, so I would have thought this would not have to be in the js delivered to the client.

My app dir setup is:
<img width="152" alt="image" src="https://github.com/payloadcms/next-payload/assets/709418/ada2896f-ecf7-43ae-8f71-4c5f73f44822">

And the bundles for the `/app/(website)/[[...path]]/page` routes looks like:
<img width="1240" alt="image" src="https://github.com/payloadcms/next-payload/assets/709418/dbec2bef-4cc3-44d4-94ca-0eef37d27be9">

After speaking with others on the payload discord we found that any routes where the local api was not used then payload was not bundled, but anywhere where it was, it was.  Is this expected?

**Comment by JarrodMFlesch** [comment]
@adampilks are you using the `@next/bundle-analyzer` plugin? Can you paste in your steps so I can repro this easily?

**Comment by IAmNatch** [comment]
I've seen this in my app as well, but previously only by looking at the network logs and searching for payload fields in the chunks. 

I was able to reproduce this with the `next-payload-demo` and `@next/bundle-analyzer`.

My repro steps were as follows:
1. Clone repo and follow set up instructions (excluding S3 plugin).
2. Install `@next/bundle-analyzer` and install it as outlined in its readme. 
3. Create a page within the admin
4. run `yarn dev` -- This will open up some bundle analyzer pages, but its not accurate yet, as we haven't really loaded a page yet. 
5. Visit the page you've created (in my case `localhost:3000/home`
6. This will generate a new `.next/analyze/client.html`, which should be visible in the next logs. From there, if it doesn't open by itself, you can open it yourself in your browser. 

I've attached my own results as image and html, you can see that payload (in its entirety I think) is leaking into both the layout and the page chunk.

<img width="1698" alt="image" src="https://github.com/payloadcms/next-payload/assets/15078788/1223b62a-d245-4f68-8500-9388b427c8ed">
[client.html.zip](https://github.com/payloadcms/next-payload/files/12470988/client.html.zip)

**Comment by adampilks** [comment]
@JarrodMFlesch were the steps provided by @IAmNatch sufficient or do you still need something from me?

**Comment by klaudgrave** [comment]
Any updates on this one? I can confirm that the issue occurs anywhere you import getPayloadClient and is basically triggered by `import { getPayload } from "payload/dist/payload";` in getPayloadClient.

Payload's CSS is also being loaded on the website's frontend when using getPayloadClient.

**Comment by jmikrut** [comment]
Just a quick update here: we have some solutions in mind that can potentially solve all of this.

The whole Payload team has been working toward our upcoming 2.0 release, but we are nearing a point where we will be able to dedicate some time back to this repo. I think we will be able to solve this entirely. 

And there’s lots more in store actually. Give us a bit and we will follow up here with some solutions. I appreciate everyone’s patience!

**Comment by adampilks** [comment]
@jmikrut Do you have a rough idea when this might be looked at?

**Comment by inadeqtfuturs** [comment]
Bumping this as a problem we're also encountering w/ a similar set up.

**Comment by 0xPT** [comment]
Yes, exact same problem. Having this in the client bundle is ultimately causing our Core Web Vitals to fall into the "Needs Improvement" category. Going to probably shift to HTTP requests since we're using SSG. However, quite the headache.

![Screenshot 2024-01-16 at 3 09 00 AM](https://github.com/payloadcms/next-payload/assets/106483620/891665f4-d447-46e8-bb72-4e3960158371)

**Comment by hatsumatsu** [comment]
Does this only happen using next's app router and RSC or with the pages router as well?

**Comment by inadeqtfuturs** [comment]
> Does this only happen using next's app router and RSC or with the pages router as well?

Just tested this morning -- using the pages router, `paylaod` is not bundled with pages that use `getStaticProps` or `getServerSideProps`. So looks like it's something related to the `app` router.

**Comment by hatsumatsu** [comment]
> > Does this only happen using next's app router and RSC or with the pages router as well?
> 
> Just tested this morning -- using the pages router, `paylaod` is not bundled with pages that use `getStaticProps` or `getServerSideProps`. So looks like it's something related to the `app` router.

Good to know! You are still using next@13 , though?

**Comment by inadeqtfuturs** [comment]
> > > Does this only happen using next's app router and RSC or with the pages router as well?
> > 
> > 
> > Just tested this morning -- using the pages router, `paylaod` is not bundled with pages that use `getStaticProps` or `getServerSideProps`. So looks like it's something related to the `app` router.
> 
> @inadeqtfuturs Good to know! You are still using next@13 , though?

Correct. I've tested with various `13.5.xx` versions of `next`.
