### ISSUE TITLE
Aliases broke with latest version 0.34

### ISSUE THREAD

**Issue by ScottEAdams** [payloadcms/next-payload#59]
No biggy (I think) but the latest 0.34 release broke some path aliases in payload.config.ts

I had this previously:

`import Users from '@/payload/collections/Users'`

Which threw

`Error: Cannot find module '@/payload/collections/Users'`

and fixed by

`import Users from './collections/Users'`

tsconfig.json:

```
    "paths": {
      "@/*": ["./src/*"]
    }
```

**Comment by walid-mos** [comment]
This seems to be a local problem with your tsconfig, as this package can't modify it.

Try maybe reload your vscode app ?

**Comment by imCorfitz** [comment]
I noticed same issue. I updated to latest version after @JarrodMFlesch informed me about another fix having been made. It seems to have been introduced after `baseUrl: path.resolve(__dirname),` was added in `loadPayloadConfig.js`. If I set it back to `undefined` manually in the package, the error is gone.

**Comment by JarrodMFlesch** [comment]
Interesting, I am wondering what the default should be for baseUrl if the current directory does not work 🤔

**Comment by imCorfitz** [comment]
So.. I noticed that everything works, if I add `"baseUrl": ".",` to my `tsconfig.json` file. Basically it seems that setting `baseUrl: path.resolve(__dirname)` in `loadPayloadConfig.js` sets the default baseUrl to be inside the `/payload` directory. That's why relative paths are still working I guess?

**Comment by JarrodMFlesch** [comment]
I just tested this and was able to repro. Setting baseUrl to `path.resolve()` in the loadPayloadConfig file fixes it. I will publish a release here in a minute 👍

**Comment by walid-mos** [comment]
Did not had time to test it yet, but i wanted to ask you if you had set « baseUrl » in tsconfig

If the problem comes from here, then it’s a tsconfig issue as the baseUrl is mandatory to make paths work (as described in their documentation)

**Comment by JarrodMFlesch** [comment]
Fixed in `0.0.35` see this commit [b2c3068](https://github.com/payloadcms/next-payload/commit/b2c306894eefd21131ff8ca6d4c322ef5d9506f0).

**Comment by ScottEAdams** [comment]
Thanks @JarrodMFlesch . Like I said, no biggy but might catch someone out ;)
