### ISSUE TITLE
seed in next-payload

### ISSUE THREAD

**Issue by mjkohan** [payloadcms/next-payload#67]
Hello, I'm attempting to implement multi-tenancy using the payload examples provided in Next-Payload. In the example code within server.ts:
```
const start = async (): Promise<void> => {
  await payload.init({
    secret: process.env.PAYLOAD_SECRET,
    mongoURL: process.env.MONGODB_URI,
    express: app,
    onInit: () => {
      payload.logger.info(`Payload Admin URL: ${payload.getAdminURL()}`)
    },
  })

  if (process.env.PAYLOAD_SEED === 'true') {
    payload.logger.info('---- SEEDING DATABASE ----')
    await seed(payload)
  }

  app.listen(3000)
} 
```

Where and how should I call this function in Next-Payload? Currently, I am unable to log into the payload panel because I do not have any users.

**Comment by JarrodMFlesch** [comment]
You could try doing this inside your onInit function, that function passes you the payload client back as the only arg, maybe try passing that to your seed function? I haven't tested this but I feel like it should work. Also if you have no users then the create user screen should pop up under the /admin route.

**Comment by mjkohan** [comment]
> You could try doing this inside your onInit function, that function passes you the payload client back as the only arg, maybe try passing that to your seed function? I haven't tested this but I feel like it should work. Also if you have no users then the create user screen should pop up under the /admin route.

thanks.  the final code in payloadClient.ts :
export const getPayloadClient = async () => {
  if (cached.client) {
    return cached.client
  }

  if (!cached.promise) {
    cached.promise = await getPayload({
      // Make sure that your environment variables are filled out accordingly
      mongoURL: process.env.MONGODB_URI as string,
      secret: process.env.PAYLOAD_SECRET as string,
      config: config,
    })
  }

  try {
    cached.client = await cached.promise
  } catch (e) {
    cached.promise = null
    throw e
  }
   await seed(cached.client)  
  return cached.client
};

**Comment by JarrodMFlesch** [comment]
@mjkohan AH, I knew what you were asking rang a bell. We just did something similar for our nextjs-custom-server example, check it out if you are interested!

https://github.com/payloadcms/payload/blob/master/examples/custom-server/src/getPayload.ts
