### ISSUE TITLE
Module Not Found: @payloadcms/next-payload/getPayload

### ISSUE THREAD

**Issue by akanshSirohi** [payloadcms/next-payload#76]
I have integrated next-payload into my NextJS 13 but it is showing the error below, any quick fix for that? 

![image](https://github.com/payloadcms/next-payload/assets/34837239/cca21bc4-6c1b-4a41-89ed-43f57d7aa69b)

**Comment by SimonPuckey** [comment]
Also having this problem and another `module-not-found` issue. Be good to know if Im doing something incorrectly somehow or if the package needs fixing. was really looking forward to using this 😞

<img width="517" alt="Screenshot 2023-10-01 at 22 01 32" src="https://github.com/payloadcms/next-payload/assets/5788962/da7b1d28-3bbb-466f-91d2-4939495a5fd3">

**Comment by akanshSirohi** [comment]
@SimonPuckey Delete node_modules and use yarn to install the modules again, it worked for me. It is working but now I have some logs showing in my console but it is working fine. You can try that too and let me know if you got those logs too or how you solved them if you found any solution.

**Comment by nathan-impression** [comment]
![Screenshot 2023-10-23 at 16 43 43](https://github.com/payloadcms/next-payload/assets/122875177/afd6e363-546b-46f6-aa22-3a01917042a3)

Also getting this issue

**Comment by Trugamr** [comment]
Make sure you have config path present in `.env` or `.env.local`
```
PAYLOAD_CONFIG_PATH=payload/payload.config.ts
```
Default export `getPayloadClient()`
```
const getPayloadClient = async () => {
   ...
}


export default getPayloadClient
```

**Comment by guillaumeLamanda** [comment]
I also getting into this one.  
I tried to switch from `pnpm` to `yarn` but it didn't fix the issue.  
I do have `PAYLOAD_CONFIG_PATH` env key pointing to my payload config (for me: `src/payload/payload.config.ts`)

**Comment by wiggindev** [comment]
> Make sure you have config path present in `.env` or `.env.local`
> 
> ```
> PAYLOAD_CONFIG_PATH=payload/payload.config.ts
> ```
> 
> Default export `getPayloadClient()`
> 
> ```
> const getPayloadClient = async () => {
>    ...
> }
> 
> 
> export default getPayloadClient
> ```

The default export of `getPayloadClient` fixed it for me

**Comment by JarrodMFlesch** [comment]
Hey all, this likely has to do with your next.config.js file. You can read more about what needs to be done here: https://github.com/payloadcms/next-payload/#4-add-withpayload-to-your-nextconfig

Specifically, you are using a src folder, so you will need to update the `configPath` and the `payloadPath` in that file.
