### ISSUE TITLE
Endpoints for Bulk operations are missing

### ISSUE THREAD

**Issue by leonardstruck** [payloadcms/next-payload#8]
The PATCH and DELETE Endpoints for Bulk operations are missing in the `api/[collection]/index.ts` handler.

**Comment by DanRibbens** [comment]
I added these here: 815321d9c1b11812e41a0cbd8a1a99f6707b985d on the branch @JarrodMFlesch is working on.

It could use some testing, I'll leave this open until it all gets merged.

**Comment by JarrodMFlesch** [comment]
These are now merged into the latest. Will release on npm soon!
