### ISSUE TITLE
`Error [ERR_REQUIRE_ESM]: require() of ES Module` error when using component in /pages instead of /app folder 

### ISSUE THREAD

**Issue by valerioleo** [payloadcms/next-payload#88]
In my project, we trying to integrate next-payload. However we still make use of the traditional /pages folder and we won't be moving those components any time soon.

I have noticed that, differently from components in the /app folder, any component in the /pages folder will break if trying to import a node_module.

I have created a very simple repro here:
https://github.com/payloadcms/next-payload-demo/compare/main...valerioleo:next-payload-demo-fork:main

1. clone repo
2. `yarn install`
3. `yarn dev`
4. navigate to localhost:3000/test-page

--- 

I have tried to debug it without success, my hunch is that the use of `@swc/register` inside the `withPayload` is complicating things, however I couldn't find a way to fix it yet. I'll keep trying.

**Comment by denolfe** [comment]
Your problem here is the package you are attempting to use `@uidotdev/usehooks` is ESM-only and is not able to be used in CJS projects.

**Comment by valerioleo** [comment]
> Your problem here is the package you are attempting to use `@uidotdev/usehooks` is ESM-only and is not able to be used in CJS projects. @denolfe 

To further investigate if the issue is a limitation of Payload being a CJS, I have added the `@uidotdev/usehooks` into a component that is imported using the /app folder. In that case it worked perfectly. You can see it [here](https://github.com/payloadcms/next-payload-demo/compare/main...valerioleo:next-payload-demo-fork:main#diff-fc1c82429cf4050593686bd9fbff643323fd2622b9dbc4f70307f19b6ae9d5d8R3).

As I see it, this strengthen the thesis that it's `withPayload` that is messing something up with the transpiration of files in the /pages folder.

**Comment by denolfe** [comment]
This looks like an issue w/ how yarn v1 resolves dependencies. The workaround is here: https://github.com/payloadcms/payload/issues/4109#issuecomment-1807008645

It sounds like this workaround will work here as well. Let me know if it does not, and I will reopen.
