### ISSUE TITLE
req.query.where is undefined

### ISSUE THREAD

**Issue by leonardstruck** [payloadcms/next-payload#9]
`req.query.where` is undefined in `pages/api/[collection]/index.ts`.

Stumbled upon this while trying to implement the bulk operation endpoints myself. It looks like the `req.query` object isn't deserialized properly:

```javascript
{
  locale: 'en',
  depth: '0',
  draft: 'true',
  page: '1',
  'where[or][0][email][like]': 'testasdasd',
  limit: '10',
  invoke: '39c3af95-edda-4797-bae1-a4fcaf31102f',
  collection: 'users'
}
```
(`req.query` on a search request)

**Comment by JarrodMFlesch** [comment]
This has been patched up and will be released with the next npm release today 👍
